### PR TITLE
Update og:image

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Solves #299 
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
@palnabarun need your deploy on this as the faster it uploads the faster platforms pick it up.

### CODE REVIEW

**Comment by palnabarun** [comment]
Is `logosmall.png` supposed to be the older one?

**Comment by vipulgupta2048** [comment]
@palnabarun The logosmall.png is the old logo that we were using in the previous theme. The blue Bangalore PyCon India.

**Comment by palnabarun** [comment]
On Fri, Sep 4, 2020 at 6:21 PM Vipul Gupta <notifications@github.com> wrote:

> @palnabarun <https://github.com/palnabarun> The logosmall.png is the old
> logo that we were using in the previous theme. The blue Bangalore PyCon
> India.
>
I know that. My question was why are we using that? Shouldn't we be using a
new design for that too?

**Comment by vipulgupta2048** [comment]
@palnabarun We weren't using it per se. It seems to be me that it wasn't deleted when we migrated to the new theme.

**Review by vipulgupta2048 — COMMENTED** [review]
@palnabarun If this is good to go, can we merge this ASAP?

**Pull request merged**
