### PR TITLE
Refactor the development workflow

### LINKED ISSUE #200: Server stays running even after SIGINT
Even after pressing `ctrl + c`, the server keeps running in the background.

This is annoying because while switching branches, random lines are printed in the shell and there seems to be no way to stop this as well(other than pressing `ctrl + c` each time this is done to recover the cursor)

Screen Shot 2019-05-08 at 23 26 42

### PR DESCRIPTION
**Pull request by palnabarun**
See commit messages and subjects for more context on the changes.

Supersedes and close #201, #273
Fixes #200

### CODE REVIEW

**Comment by ananyo2012** [comment]
Also you should remove the develop_server script and add the make servecommand to the README

**Comment by palnabarun** [comment]
> There are a bunch of Warning coming due to the use of {filname} where ideally {static} needs to be used in Pelican v4.

The warnings are unrelated to 2020. They are all 2019 static linking issues. They will be cleaned up in a follow up PR.

> add the make serve command to the README

Thanks for the heads up. :+1:

**Comment by palnabarun** [comment]
@ananyo2012 -- I have consolidated the Makefile, even more, making things even simpler. Also, the changes are already tested on production.

PS: The netlify build on your personal repository is breaking probably due to the manual configuration of the build command. Set it to `pelican content` or `make html`.

**Comment by ananyo2012** [comment]
@palnabarun I have removed the netlify site from my account. You can go ahead and merge this.

**Comment by palnabarun** [comment]
@ananyo2012 -- Thanks! :+1:

**Comment by palnabarun** [comment]
PS: For anyone looking at it much later, the build would show to be failed because of a misconfigured `deploy/netlify` build target.

**Pull request merged**
