### PR TITLE
AQR announcement for PyCon India 2018

### PR DESCRIPTION
**Pull request by chirag200666**

### CODE REVIEW

**Comment by ananyo2012** [comment]
@chirag200666 Can you use the new summary markers as discussed in #151 ?

**Comment by vipulgupta2048** [comment]
@ananyo2012 Should I make a PR to open up the sponsor section and add AQR

**Comment by chirag200666** [comment]
@ananyo2012 , @vipulgupta2048 
I have changed the format from .md to .rst and in the interest of time have merged it. 
@vipulgupta2048 
can you please implement the changes you have suggested.
Thanks

**Comment by ananyo2012** [comment]
@vipulgupta2048 I have taken care of some of your points in #158 . Answers to other mentioned below

- Logo is kept above the summary
- I have used the image link from `inpycon2018` github repo. Images in repo are stable and won't be lost.  Didn't add the same image in 2 places hence.
- I have linked the AQR image to their website. That should be enough right ?

**Pull request merged**
