### PR TITLE
Adding google as sponsers

### PR DESCRIPTION
**Pull request by Rohithgilla12**

### CODE REVIEW

**Comment by Rohithgilla12** [comment]
#178

**Comment by Rohithgilla12** [comment]
screenshot 2018-09-26 21 08 24
screenshot 2018-09-26 21 08 31

**Comment by ananyo2012** [comment]
LGTM. But please remove the previous commits for Corteva. And also remember to work in separate branches from now on.

**Comment by Rohithgilla12** [comment]
Yeah sure bro

**Comment by Rohithgilla12** [comment]
Yeah sure, will do it by 16:00

**Comment by Rohithgilla12** [comment]
Yeah sure,will do by 16:00

**Pull request closed without merging**
