### PR TITLE
Add 2021/workshops blog post

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

* **Please check if the PR fulfills these requirements**

- [ ] Screenshots for changes (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Closes https://github.com/pythonindia/inpycon2021-tasks/issues/86

**Review by realslimshanky — CHANGES_REQUESTED** [review]
@vipulgupta2048  Please rebase your branch with master in order to resolve Netlify build error.

**Review by raukadah — APPROVED** [review]

**Review by raukadah — APPROVED** [review]
Good Job \o/

**Review by raukadah — APPROVED** [review]
\o/ Good to go

**Pull request merged**
