### PR TITLE
Fixes bug with page title

### LINKED ISSUE #34: Page title is fixed for all pages and showing "2015 in Bangalore"
This needs to be dynamic and set to current page title - https://github.com/pythonindia/inpycon-blog/blob/master/themes/inpycon/templates/base.html#L20

Now it's just showing "PyCon in Bangalore in 2016" for all pages.

### PR DESCRIPTION
**Pull request by iambibhas**
This fixes #34. Also, added the `devserver` command that was in makefile but didn't work.

### CODE REVIEW

**Comment by kracekumar** [comment]
+1. @theskumar ?

**Comment by theskumar** [comment]
The change needs to be in `inpycon2016` theme.

**Comment by iambibhas** [comment]
`inpycon2016` didn't exist when I sent the PR. Just pushed. Check.

**Comment by theskumar** [comment]
Looks good to me @iambibhas, thanks. I don't have merge access to this repo. @kracekumar @vnbang2003 help out please.

**Comment by kracekumar** [comment]
@theskumar You have the access now.

**Pull request merged**
