### PR TITLE
2024 sponsor manage engine site 24x7

### PR DESCRIPTION
**Pull request by Sc0rpi0n101**

### CODE REVIEW

**Review by bhansa — CHANGES_REQUESTED** [review]
Image is missing

**Comment by Sc0rpi0n101** [comment]
yes, the drive link in the issue is a pdf. Can you please give a png for the logo. @bhansa @WatchfulHitman

**Comment by WatchfulHitman** [comment]
> yes, the drive link in the issue is a pdf. Can you please give a png for the logo. @bhansa @WatchfulHitman

That was provided by the sponsor itself

**Comment by WatchfulHitman** [comment]
> > yes, the drive link in the issue is a pdf. Can you please give a png for the logo. @bhansa @WatchfulHitman
> 
> That was provided by the sponsor itself 2 links

https://drive.google.com/open?id=1_mctD7zwjc5QWMH8C7-V8TXf4_gu3iZH
https://drive.google.com/open?id=13u62ZhFE9caZ5qPGNB7sQnhhJhidl_e7

**Review by anistark — APPROVED** [review]

**Pull request merged**
