### PR TITLE
Kill Pelican process on exit

### PR DESCRIPTION
**Pull request by astronomersiva**
Addresses https://github.com/pythonindia/inpycon-blog/issues/200.

Cleans up the Pelican server on process exit.

### CODE REVIEW

**Comment by astronomersiva** [comment]
The current script has some flaws:

- The server runs in the background even after SIGINT. This causes interference with the terminal like described in the above issue.
- Even though the server is running in the background, it is not accessible from the browser. 
- If I start a server multiple times, there is a Pelican process started for each of those times and they are not getting cleaned up.

This change calls the `shut_down` already used in the script on process exit. It causes no other change in development other than addressing the above points.

**Comment by astronomersiva** [comment]
cc: @ananyo2012

**Comment by vipulgupta2048** [comment]
@ananyo2012 Should we merge this?

**Comment by palnabarun** [comment]
This is good according to me. :+1:

**Comment by palnabarun** [comment]
Bdw, this is a change to the development server. The blog is generated as a static site and deployed.

**Comment by ananyo2012** [comment]
Yes this is a low priority issue. Will check once and merge.

**Comment by vipulgupta2048** [comment]
@ananyo2012 I have seen what @astronomersiva and I have been having the same issue. I had to kill all the pelican process to stop the development server from reloading. I think this would help a lot. Please review and merge.

**Comment by ananyo2012** [comment]
@vipulgupta2048 For now please use `make devserver` and `make stopserver` commands. That is the intended use case.

@astronomersiva mentioned in #200 that startserver/stopserver is not an user friendly flow in a development server.The correct fix would be to kill the pelican regenerate process once the server is stopped. Pelican v4 already has a better mechanism to handle this using `-l` option. 

I will add another target `startserver` that will use the current flow and update the current devserver target with th Ctrl+C exit based flow.

**Comment by astronomersiva** [comment]
@ananyo2012 

> The correct fix would be to kill the pelican regenerate process once the server is stopped.

That is precisely what this PR does.

> For now please use make devserver and make stopserver commands. That is the intended use case.

The use case here is to have a command that when run, starts a server and when `ctrl + c` is pressed, stops whatever it's supposed to be doing. I don't think having two separate commands to start and stop a server is a good idea.

Also, here is what `make stopserver` does,

```
stopserver:
	kill -9 `cat pelican.pid`
	kill -9 `cat srv.pid`
	@echo 'Stopped Pelican and SimpleHTTPServer processes running in background.'
```

This is basically what @vipulgupta2048 has been doing with `killall pelican` too. I just have a simple question - why to ask people to do all this when the ideal solution is to just gracefully exit the server(as done in this PR).

> I will add another target startserver that will use the current flow and update the current devserver target with th Ctrl+C exit based flow.

Why though?

**Comment by ananyo2012** [comment]
I am okay with deprecating the start/stop flow all together. The current fix has some spurious messages like

```
cat: /home/ananyo/inpycon-blog/srv.pid: No such file or directory
HTTP server PIDFile not found
cat: /home/ananyo/inpycon-blog/pelican.pid: No such file or directory
Pelican PIDFile not found
....
....
Pelican and HTTP server processes now running in background.
Stopping HTTP server
Stale PID, deleting
```
We should cleanup the script and remove whatver isn't required.

**Comment by ananyo2012** [comment]
Anyways I created #273 with the points I mentioned earlier. Let me know if we want to deprecate the start/stop/restart options I can go ahead and do that

**Comment by astronomersiva** [comment]
```
cat: /home/ananyo/inpycon-blog/srv.pid: No such file or directory
HTTP server PIDFile not found
cat: /home/ananyo/inpycon-blog/pelican.pid: No such file or directory
Pelican PIDFile not found
....
Pelican and HTTP server processes now running in background.
```
I am not sure why this is happening to you. I don't think this is related to this change either.

**Comment by palnabarun** [comment]
Quoting myself from #273, https://github.com/pythonindia/inpycon-blog/pull/273#issuecomment-633273076

**Comment by palnabarun** [comment]
```
cat: /home/ananyo/inpycon-blog/srv.pid: No such file or directory
HTTP server PIDFile not found
cat: /home/ananyo/inpycon-blog/pelican.pid: No such file or directory
Pelican PIDFile not found
....
....
Pelican and HTTP server processes now running in background.
Stopping HTTP server
Stale PID, deleting
```

@astronomersiva is correct. These errors are not directly related to the changes in this PR but a side effect of them. This PR tries to correct the broken workflow  followed till date. See below why I say so.

Running `make devserver` calls `./develop_server restart 8000`, which tries to cleanup shit scattered by earlier runs of the same and then spin up fresh instances of generator and server. The process of cleanup the shit then shows the above messages as the PID files have already been cleaned by when `shut_down` got called by the trap.

cc: @ananyo2012 ^^^

**Comment by ananyo2012** [comment]
Yup that explains it. Let's cleanup the things not required as per https://github.com/pythonindia/inpycon-blog/pull/273#issuecomment-633278392

**Pull request closed without merging**
