### PR TITLE
Link contributer guidelines to readme | borrowed issue and PR templates

### PR DESCRIPTION
**Pull request by a2un**
Link contributer guidelines to readme | borrowed issue and PR templates. In continuation to PR #135

### CODE REVIEW

**Comment by a2un** [comment]
I used git rebase however somehow dint work this time.

**Comment by vipulgupta2048** [comment]
@a2un Hi, please read this article for squashing commits using rebase https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/ 
If you need more help, ping on the discord channel that we have.

**Comment by vipulgupta2048** [comment]
@a2un Hi, are you still working on the PR?
@ananyo2012  Can we close this PR, due to inactivity or wait for a little more. 
@utkarsh2102 Watch this space, please. Since you showed interest in fixing the issue.

**Comment by ananyo2012** [comment]
@vipulgupta2048 The work is already complete I guess. Do you have any suggestions to make or I will merge this.

**Comment by a2un** [comment]
Hi @everyone..

**Comment by ananyo2012** [comment]
Hi @a2un please don't tag "@everyone" . Its a different user in GitHub.
They is nothing such as all here in GitHub

**Pull request closed without merging**
