### PR TITLE
Update theme for the 2021 blog

### PR DESCRIPTION
**Pull request by Sc0rpi0n101**
CC: @sayanchowdhury @noblebatman @SaptakS @palnabarun

### CODE REVIEW

**Review by sayanchowdhury — APPROVED** [review]
Overall looks good to me

/cc @palnabarun @SaptakS Please review too.

**Comment by palnabarun** [comment]
Just my opinions, I think the pagination needs to be centered and this weird white break between the paginator and the footer needs to be removed.
image

**Comment by Sc0rpi0n101** [comment]
+1  We can even update with like some buttons or something that look better with the theme. 

I'm not even sure why the white break is there tbh.

**Comment by palnabarun** [comment]
I am curious as well about the white break. I couldn't find anything by inspecting.

Centering the pagination is a simple fix.

```
.paginator {
  text-align: center
}
```

**Pull request merged**
