### PR TITLE
Added FOSSEE Sponsor Post

### LINKED ISSUE #159: Add sponsors blog posts
Sponsor Blog posts needs to be created as per the given information

Description & logos at:
https://github.com/pythonindia/inpycon2018/issues/151

### PR DESCRIPTION
**Pull request by rahulkumaran**
Fixes #159

Added a blog post for FOSSEE. This is with reference to the post on discord asking us to do the same.

Also, right now I've added the logo to `content/images/` directory as I couldn't find the logo for FOSSEE in the `inpycon2018/img/sponsors` directory.
I've sent a PR for adding the image to inpycon2018 repo. Please review that

PS: The link that exists now in this blog post is just temporary. Will change it once the PR in the inpycon2018 repo is merged to add the logo of FOSSEE

### CODE REVIEW

**Comment by rahulkumaran** [comment]
fossee

That's how it looks @ananyo2012

**Comment by ananyo2012** [comment]
This is on-hold until the social media team is ready to announce it.

**Comment by vipulgupta2048** [comment]
A good thing to practice everytime is to refer back to the issue that you are fixing. Something like.
Fixing #159 
This helps other people see progress on a issue from one place.

**Comment by rahulkumaran** [comment]
@vipulgupta2048
Yes, my bad
Forgot to reference the issue! Will update it right away! Sorry for that

**Comment by realslimshanky** [comment]
@rahulkumaran any update?

**Comment by rahulkumaran** [comment]
@realslimshanky
Hey, everything is ready. It's just that @ananyo2012 is waiting for the social media team to announce fossee as a sponsor.

**Comment by ananyo2012** [comment]
We have got an word from Sponsorship team to wait on this announcement. We will wait Till we get a confirmation from them

**Comment by realslimshanky** [comment]
@ananyo2012 I guess this is good to go.

**Pull request merged**
