### PR TITLE
Adding corteva as gold sponser

### PR DESCRIPTION
**Pull request by Rohithgilla12**
* **Please check if the PR fulfills these requirements**

- [x] Screenshots for changes (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Update

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

#177

### CODE REVIEW

**Comment by Rohithgilla12** [comment]
screenshot 2018-09-26 13 30 36
screenshot 2018-09-26 at 1 30 47 pm

**Comment by ananyo2012** [comment]
@Rohithgilla12 Can you include the headings in bold as well ? We don't want to modify their description given to us.

**Comment by ananyo2012** [comment]
Not sure why netlify preview url https://deploy-preview-180--reverent-ride-346855.netlify.com/ is not showing all the blogs. Will have to check the issue.

**Comment by Rohithgilla12** [comment]
@ananyo2012 added the heading

**Comment by ananyo2012** [comment]
Looks good. Merging this in.

**Pull request merged**
