### PR TITLE
Removed all the warning messages according to issue #276

### LINKED ISSUE #276: Cleanup warning messages from previous year blog posts while generating content
**This issue is ideal for anyone new getting started contributing to the development of blogs and wants to learn more about how pelican works. This can be taken up by more than one person and the work can be split up.**

_**MAINTAINERS/EXISTING CONTRIBUTORS please stay away from this issue for the time being (say if by July 1st no new contributors take it up, feel free to fix it yourself).**_

Knowledge required
---
1. Python 3
2. Pelican
3. HTML
4. CSS

Steps to reproduce
---
Setup your development environment according to [README][1]
```
$ make serve
...
(You will see all the above warnings)
```

Following are the warnings churned by `make serve`:
```
WARNING: {filename} used for linking to static content images/sponsors/grofers.png in blog/2019-announcing-grofers-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/instazen.png in blog/2019-announcing-instazen-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/merit.png in blog/2019-announcing-merit-group-gold-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/zilogic.png in blog/2019-announcing-zilogic-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/appviewx.png in blog/2019-announcing-appviewx-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/lti.png in blog/2019-announcing-lti-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content imagSteps to reproduce
---
Setup your development environment according to [README][1]
```
$ make serve
...
(You will see all the above warnings)
```es/sponsors/microsoft.png in blog/2019-announcing-microsoft-platinum-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/bloomberg.png in blog/2019-announcing-bloomberg-gold-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/kla.png in blog/2019-announcing-kla-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/airasia.png in blog/2019-announcing-airasia-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/episource.png in blog/2019-announcing-episource-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/reckonsys.png in blog/2019-announcing-reckonsys-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/atonarp.png in blog/2019-announcing-atonarp-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/guvi.png in blog/2019-announcing-guvi-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/mjit.png in blog/2019-announcing-mjit-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/redhat.png in blog/2019-announcing-redhat-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/zeomega.png in blog/2019-announcing-zeomega-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/toyota.jpg in blog/2019-announcing-toyotaconnected-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/cppsecrets.png in blog/2019-announcing-cppsecrets-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/deepsource.png in blog/2019-announcing-deepsource-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/elastic.png in blog/2019-announcing-elastic-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/thoughtworks.png in blog/2019-announcing-thoughtworks-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/ediitn.png in blog/2019-announcing-ediitn-gold-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/lji.png in blog/2019-announcing-lji-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/mavenhive.png in blog/2019-announcing-mavenhive-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/dckap.png in blog/2019-announcing-dckap-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/erpnext.png in blog/2019-announcing-erpnext-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/realpython.png in blog/2019-announcing-realpython-associate-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/xapo.png in blog/2019-announcing-xapo-inkind-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/innovaccer.png in blog/2019-announcing-innovaccer-gold-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/pipal.jpg in blog/2019-announcing-pipal-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/pramati.png in blog/2019-announcing-pramati-silver-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/ericsson.png in blog/2019-announcing-ericsson-gold-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/happyfox.png in blog/2019-announcing-happyfox-gold-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/stickermule.png in blog/2019-announcing-stickermule-inkind-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/indeed.png in blog/2019-announcing-indeed-platinum-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/posters/pysangamam_2018_1.jpg in blog/2019-a-lucent-guide-to-poster-presentation.md. Use {static} instead
WARNING: {filename} used for linking to static content images/posters/pysangamam_2018_2.jpg in blog/2019-a-lucent-guide-to-poster-presentation.md. Use {static} instead
WARNING: {filename} used for linking to static content images/posters/pysangamam_2018_3.jpg in blog/2019-a-lucent-guide-to-poster-presentation.md. Use {static} instead
WARNING: {filename} used for linking to static content images/posters/why_poster.png in blog/2019-a-lucent-guide-to-poster-presentation.md. Use {static} instead
WARNING: {filename} used for linking to static content images/posters/poster_guide.png in blog/2019-a-lucent-guide-to-poster-presentation.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/madstreetden.png in blog/2019-announcing-madstreetden-gold-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/visiblealpha.png in blog/2019-announcing-visiblealpha-gold-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/asldevi.jpg in blog/2019-announcing-keynote-speaker-for-pycon-india-2019-asldevi.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/aws.png in blog/2019-announcing-aws-gold-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/jetbrains.png in blog/2019-announcing-jetbrains-gold-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/sponsors/aqr.jpg in blog/2019-announcing-aqr-platinum-sponsor.md. Use {static} instead
WARNING: {filename} used for linking to static content images/jake-vanderplas.jpg in blog/2019-announcing-keynote-speaker-for-pycon-india-2019-jakevdp.md. Use {static} instead
WARNING: {filename} used for linking to static content images/pyladies_aroma.jpg in blog/2019-pyladies-at-pycon-india-aroma-rodrigues.md. Use {static} instead
WARNING: {filename} used for linking to static content images/david-beazley.jpg in blog/2019-announcing-keynote-speaker-for-pycon-india-2019-dabeaz.md. Use {static} instead
WARNING: {filename} used for linking to static content images/ines.jpg in blog/2019-announcing-keynote-speaker-for-pycon-india-2019-ines-montani.md. Use {static} instead
WARNING: {filename} used for linking to static content images/2016-van.jpg in blog/announcing-third-keynote-speaker-for-pycon-india-2016.md. Use {static} instead
```

[1]: https://github.com/pythonindia/inpycon-blog/blob/master/README.md

### PR DESCRIPTION
**Pull request by rakshakannu**
According to the issue #276 all the warning messages had to be removing while generating content.
I have completed the work.
below is the screenshot.
[screenshot](https://drive.google.com/open?id=1rrXGaRKRHaR9DcKox2AVwEV8mch4jQBl)

Closes #276

### CODE REVIEW

**Comment by palnabarun** [comment]
@rakshakannu -- Can you please squash your commits into one?

**Comment by rakshakannu** [comment]
> @rakshakannu -- Can you please squash your commits into one?

Okay sure

**Comment by rakshakannu** [comment]
@palnabarun I'm not able to squash commits after several tries! (I'm new to this!)

**Comment by palnabarun** [comment]
@rakshakannu -- Please have a look here -> https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Comment by rakshakannu** [comment]
> @rakshakannu -- Please have a look here -> https://github.com/wprig/wprig/wiki/How-to-squash-commits

yes, tried this several times, not getting it

**Comment by ananyo2012** [comment]
You can try this
```
git reset HEAD~52
git add .
git commit -m "commit message"
```

**Comment by palnabarun** [comment]
@rakshakannu -- Are you getting any error when following the rebase workflow?

**Comment by rakshakannu** [comment]
> @rakshakannu -- Are you getting any error when following the rebase workflow?

Yes, after squashing the commits it's not getting updated even after several tries!

**Comment by palnabarun** [comment]
@rakshakannu -- Can you post a screenshot of `git log` before and after you perform the `git rebase -i master`? Also, a screenshot of the vim window where you are shown the rebase options?

**Comment by palnabarun** [comment]
@rakshakannu -- Are you still working on this?

**Comment by sayanchowdhury** [comment]
@rakshakannu Are you still working on this? Feel free to ping us for issues/queries.

@palnabarun We can wait for a couple of days more, if not then we can squash from our side and merge.

**Comment by palnabarun** [comment]
@sayanchowdhury -- Agreed! I will squash the commints on the weekend, if there is no response.

**Pull request merged**
