### PR TITLE
Added Blog Post for Sliver Sponsors [Zeomega, PSF, FOSSEE]

### PR DESCRIPTION
**Pull request by vipulgupta2048**
@realslimshanky Do review the content.

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@realslimshanky review ?

**Comment by realslimshanky** [comment]
@vipulgupta2048 would you please make the images a little bigger. As compared to the image in Pipal Academy blog these three blogs have smaller images.

**Comment by vipulgupta2048** [comment]
On it.

**Comment by realslimshanky** [comment]
@vipulgupta2048 please state the source of the write-ups here so others can review the content.

**Comment by vipulgupta2048** [comment]
Sources for the blog post are as follows:-
1. **For PSF** - https://www.python.org/psf/ 
2. **For FOSSEE** - http://fossee.in/about-us 
                             - http://python.fossee.in/about/
3. **For zeomega** - http://www.zeomega.com/about-zeomega-software-solutions/
                                - http://www.zeomega.com/about-zeomega-software-solutions/zeomega-company-overview/

**Comment by realslimshanky** [comment]
@vipulgupta2048 please resolve conflicts

**Comment by vipulgupta2048** [comment]
Done. Ready to merge now.

**Comment by akshayaurora** [comment]
@vipulgupta2048 thanks

**Pull request merged**
