### PR TITLE
Add setup for terminating pelican regenerate process on exiting server

### LINKED ISSUE #200: Server stays running even after SIGINT
Even after pressing `ctrl + c`, the server keeps running in the background.

This is annoying because while switching branches, random lines are printed in the shell and there seems to be no way to stop this as well(other than pressing `ctrl + c` each time this is done to recover the cursor)

Screen Shot 2019-05-08 at 23 26 42

### PR DESCRIPTION
**Pull request by ananyo2012**
Added target 'startserver' and fixed the behavior for server start/stop flow

Updated 'devserver' target to kill regenerate process on exiting server

Fixes #200

### CODE REVIEW

**Comment by astronomersiva** [comment]
@ananyo2012, why should there be two different mechanisms to start a dev server? Is there any reason for having a server running in the background when it cannot even be used?

**Comment by ananyo2012** [comment]
@astronomersiva There was a bug in the start function so the server was not running in background. I fixed it in [this line](https://github.com/pythonindia/inpycon-blog/pull/273/files#diff-02806846ea68d475e0a7696c86cb7f76R70)

**Comment by ananyo2012** [comment]
The background running is the traditionally used process which is a part of the Pelican utility commands. We can deprecate it if everyone decides that.

**Comment by palnabarun** [comment]
Let's not run the dev server in the background. It's a very big procedural nightmare. There is no UX improvement in doing so. The users (users here are developers for the sake of brevity) can anytime open a new terminal and run the server.

**Comment by palnabarun** [comment]
Let's think of what the user (read the developer) needs from a development server. A way to:
1. generate the content
2. run a local server which serves the generated content
3. stop the local server with proper handling

Here is the ideal UX flow to satisfy the above:
1. `make devserver`
  - should start the pelican generator in the background and echo PID to a file.
  - should start `pelican.server` and block
  - trap the `SIGINT`, `SIGTERM` and `EXIT` interrupts and kill the pelican generator which was running in the background and safely clean the environment. Notice, here the `pelican.server` PID becomes redundant as the process runs in the foreground.

2. No need for `make stopserver`, because it complicates the UX and `make devserver` cleans up its own shit.

_**Much simpler, yet effective.**_

> Note: When I looked at https://github.com/pythonindia/inpycon-blog/pull/201, the change in that PR satisfies the above UX requirement with minimal changes. (Although, `make devserver` needs to be removed)
---
To that effect, we don't even need a `make devserver`. Rename `./develop_server.sh` to `./develop-server` and change default subcommand to `start`.

**Comment by ananyo2012** [comment]
@palnabarun Yes let's deprecate the older flow and kill all pelican processes on exit. #200 does fix the issue but let's remove all redundant code and make the flow cleaner and remove all spurious messages. Also remove the make targets.

**Comment by ananyo2012** [comment]
#274 addresses this

**Pull request closed without merging**
