### PR TITLE
new blog: why should you attend pycon india 2021

### PR DESCRIPTION
**Pull request by amrrs**
* **Please check if the PR fulfills these requirements**

- [x] Screenshots for changes (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

New Blog post and a bug fix of the previous post's rendering error

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by amrrs** [comment]
Screenshot
image

**Review by vipulgupta2048 — COMMENTED** [review]
Thanks for making the PR, I have suggested changes in line. This looks good for a first draft, let's keep it brief and get this ready to publish.

**Comment by vipulgupta2048** [comment]
Hey, @amrrs Have you had a chance to look at the changes suggested? Looking forward to hearing from you.

**Comment by amrrs** [comment]
Hey @vipulgupta2048 Currently I don't have time to look into this. Iill close the PR. Thanks for reviewing it.

**Pull request closed without merging**
