### PR TITLE
Fixes #172 : Fix spelling error in Dev sprints blog post

### LINKED ISSUE #172: Spelling error in (understanding-dev-sprints-2018.md)
On line 15 and 17 in understanding-dev-sprints-2018.md renamed "Preferrably" to "Preferably" and "annouced" to "announced"

### PR DESCRIPTION
**Pull request by mechanicnitin**
On line 15 and 17 in understanding-dev-sprints-2018.md renamed "Preferrably" to "Preferably" and "annouced" to "announced"

### CODE REVIEW

**Comment by realslimshanky** [comment]
@mechanicnitin please edit PR description and include more details about the issue you are trying to solve and link to the issue number as well.

**Comment by ananyo2012** [comment]
@mechanicnitin Yes please do as Shashank said. Since this is you first contribution it is good to learn the right way to create a PR.

**Comment by mechanicnitin** [comment]
On line 15 and 17 in understanding-dev-sprints-2018.md renamed "Preferrably" to "Preferably" and "annouced" to "announced"

**Comment by ananyo2012** [comment]
@mechanicnitin Check how I edited the title and description of the PR. You can edit them both. Anways I am merging this in. Thanks for your contribution.

**Pull request merged**
